# Generated by Django 3.0.4 on 2020-04-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0002_auto_20200327_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
