# Generated by Django 3.0.4 on 2020-04-15 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_playlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
