# Generated by Django 3.0.4 on 2020-04-18 23:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_auto_20200415_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
